language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ckting0723/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true ckting0723/docker-react npm test

after_access:
  - docker build -t ckting0723/multi-client ./client
  - docker build -t ckting0723/multi-nginx ./nginx
  - docker build -t ckting0723/multi-server ./server
  - docker build -t ckting0723/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ckting0723/multi-client
  - docker push ckting0723/multi-nginx
  - docker push ckting0723/multi-server
  - docker push ckting0723/multi-worker